name: Build and Deploy Azure Function

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' 
  DOTNET_VERSION: 8.0.x  
  AZURE_FUNCTIONAPP_NAME: "ocr-function-ai-grocery"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for Azure OIDC authentication
      contents: read # Required for actions/checkout

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Setup .NET ${{ env.DOTNET_VERSION }}'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Restore Dependencies'
        run: dotnet restore AI-Grocery-app

      - name: 'Build Project'
        run: dotnet build AI-Grocery-app --configuration Release --output ./output

      - name: 'Publish Project'
        run: dotnet publish AI-Grocery-app --configuration Release --output ./publish

      - name: 'Create Deployment Zip'
        run: |
          cd ./publish
          zip -r ../publish.zip .

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: 'Deploy to Azure Function Without Kudu'
        run: |
          az functionapp deployment source config-zip \
            --resource-group AI-Grocery \
            --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
            --src ./publish.zip
